build:
    environment:
        php: '8.1'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

checks:
    php:
        code_rating: true
